### ISSUE TITLE
[IMPORTANT] Project Midterm Development Checklist

### ISSUE THREAD

**Issue by CodexLink** [CodexLink/Route88_HybridSystem#9]
At this point of time, while I was low-key (me @CodexLink ) having mental breakdown and outrage issues and keeps shouting in GC to take my shit into a serious one. I want to list this one to update myself. So that when I'm in anxiety mode, I just have to look this one to sort myself out on this particular subject called 'Database Management System'

Here are the following tasks to be completed.

- [x] There should already be a presentable UI that can be used.
- [x] The system should already be connecting to a database.
- [ ] The system should be able to perform CRUD functionalities which should be seen in the software itself (using the SQL Server Management Studio or the MySQL Terminal is only allowed for verification purposes only). Note that I should be able to see that if you updated a value in the GUI, it should reflect in the GUI before you show me that it also worked on the database side.

Part that is more important than for overall
- [ ] The System must be 50% to 70% done.
- [x] The system should have at least some form of error-handling.
- [x] The root user should not be used on the code for the connection to the database. The created user should only have the necessary permissions (you will need to show me those permissions).

When everything is checked here, we will get 50 points.

Also, take note for the part of the documentation part as well.
- [x] Show the background of the study in 1 paragraph, answering the questions(Who is the client? What do they do? What are the problems they are encountering in their business?)
contain a clearer statement of the problem (1-2 sentences only and should be derived from the background of the study),
- [x] a 1-2 sentence general objective
- [x] more specific bulleted list of features in the specific objectives
- [x] A presentable database design (ER Diagram, Crow's foot notation)

This issue will be closed if it was completed and will be transitioned to Finals Development Project

**Comment by CodexLink** [comment]
30/50. Not bad. Slightly disappointed in my case. Because of the difficulties that I went through.

Document left.

**Comment by CodexLink** [comment]
So far, two checkboxes were left unchecked. Because of CRUD functionality. We don't have an edit. and finally, the system is not yet fully completed.

We will close this and comment the final grade as we progress to the development of a final period.
